version: '3'
services:
  post_db:
    image: mongo:${VERSION_MONGODB}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${VERSION_UI}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - prometheus_net
      - front_net
    depends_on:
      - post
      - comment
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    networks:
      - front_net

  post:
    image: ${USERNAME}/post:${VERSION_POST}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - back_net
      - front_net
    depends_on:
      - post_db
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      - front_net
      - back_net

  comment:
    image: ${USERNAME}/comment:${VERSION_COMMENT}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
#      - prometheus_net
      - back_net
      - front_net

  #prometheus:
  #  image: ${USERNAME}/prometheus
  #  networks:
  #    - prometheus_net
  #  ports:
  #    - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}
  #  volumes:
  #    - prometheus_data:/prometheus
  #  networks:
  #    - back_net
  #    - front_net
  #  command:
  #    - '--config.file=/etc/prometheus/prometheus.yml'
  #    - '--storage.tsdb.path=/prometheus'
  #    - '--storage.tsdb.retention=1d'
#  node-exporter:
#    image: prom/node-exporter:v0.15.2
#    networks:
#      - prometheus_net
#      - back_net
#      - front_net
#    user: root
#    volumes:
#      - /proc:/host/proc:ro
#      - /sys:/host/sys:ro
#      - /:/rootfs:ro
#    command:
#      - '--path.procfs=/host/proc'
#      - '--path.sysfs=/host/sys'
#      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
#
#  mongo-exporter:
#    image: elarasu/mongodb_exporter
#    user: root
#    networks:
#      - prometheus_net
#      - back_net
#      - front_net
#    environment:
#      MONGODB_URL: 'mongodb://post_db:27017'
#    depends_on:
#      - post_db
#
#  blackbox-exporter:
#    image: prom/blackbox-exporter:v0.19.0
#    user: root
#    networks:
#      - back_net
#      - front_net
#    depends_on:
#      - post_db
#      - comment
#      - post
#      - ui
#
#  prometheus:
#    image: ${USERNAME}/prometheus
#    ports:
#      - '9090:9090'
#    volumes:
#     - prometheus_data:/prometheus
#    networks:
#      - back_net
#      - front_net
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#      - '--storage.tsdb.path=/prometheus'
#      - '--storage.tsdb.retention=1d'
#    depends_on:
#      - ui
#      - post
#      - comment
#      - node-exporter
#      - mongo-exporter
#      - blackbox-exporter


volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
  back_net:
#  prometheus_net:
