---
- name: Deploy node on master
  hosts: master
  become: true

  roles:
    - docker
    - node
    - master_node
    - calico

- name: Deploy node on worker
  hosts: workers
  become: true

  roles:
    - docker
    - node
    - worker_node
