---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment
  labels:
    app: reddit
    component: comment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reddit
      component: comment
  template:
    metadata:
      name: comment
      labels:
        app: reddit
        component: comment
    spec:
      containers:
      - image: zagretdinov/comment
        name: comment
        env:
        - name: COMMENT_DATABASE_HOST
          value: comment-db


#metadata:
#  name: comment-deployment
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: comment
#  template:
#    metadata:
#      name: comment
#      labels:
#        app: comment
#    spec:
#      containers:
#        - image: zagretdinov/comment
#          name: comment
