---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post
  labels:
    app: reddit
    component: post
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reddit
      component: post
  template:
    metadata:
      name: post
      labels:
        app: reddit
        component: post
    spec:
      containers:
      - image: zagretdinov/post
        name: post
        env:
        - name: POST_DATABASE_HOST
          value: post-db



#metadata:
#  name: post-deployment
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: post
#  template:
#    metadata:
#      name: post
#      labels:
#        app: post
#    spec:
#      containers:
#      - image: zagretdinov/post
#        name: post
