apiVersion: apps/v1
kind: Deployment
metadata: # Блок метаданных деплоя
  name: ui
  labels:
    app: reddit
    component: ui
spec: # Блок спецификации деплоя
  replicas: 3
  selector:
    matchLabels:
      app: reddit
      component: ui
  template: # Блок описания POD-ов
    metadata:
      name: ui-pod
      labels:
        app: reddit
        component: ui
    spec:
      containers:
      - image: zagretdinov/ui # Не забудьте подставить свой образ
        name: ui
        env:
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

# metadata:
#  name: ui-deployment
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: ui
#  template:
#    metadata:
#      name: ui
#      labels:
#        app: ui
#    spec:
#      containers:
#        - image: zagretdinov/ui
#          name: ui
