Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |v|
    v.memory = 512
  end

  config.vm.define "dockerhost" do |db|
    db.vm.box = "ubuntu/xenial64"
    db.vm.hostname = "dockerhost"
    db.vm.network :private_network, ip: "10.10.10.10"
    db.vm.provision "ansible" do |ansible|
          ansible.playbook = "playbooks/packer_docker.yml"
    end
  end
end
